- type: job
  id: FWGuardCaptain
  name: job-name-guard-captain
  description: job-description-guard-captain
  playTimeTracker: FWJobGuardCaptain
  startingGear: FWGuardCaptainGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-king

- type: startingGear
  id: FWGuardCaptainGear
  equipment:
    jumpsuit: FWClothingUniformGuardsmanCap
